export { default as Navbar } from "./Navbar";
export { default as Homepage } from "./Homepage";
export { default as ProductCatalogue } from "./ProductCatalogue";
export { default as ProductPage } from "./ProductPage";
export { default as About } from "./About";
export { default as Consultation } from "./Consultation";
export { default as Support } from "./Support";
export { default as Login } from "./Login";
export { LoginPage } from "./Login";
export { default as ForgotPassword } from "./Login/ForgotPassword";
export { default as ResetPassword } from "./Login/ResetPassword";
