export const initialCourses = [
  {
    id: 1,
    name: "Learning Gutenberg 1",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 188,
    cart: false,
  },
  {
    id: 2,
    name: "Learning Gutenberg 2",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 172,
    cart: false,
  },
  {
    id: 3,
    name: "Learning Gutenberg 3",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 107,
    cart: false,
  },
  {
    id: 4,
    name: "Learning Gutenberg 4",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 137,
    cart: false,
  },
  {
    id: 5,
    name: "Learning Gutenberg 5",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 168,
    cart: false,
  },
  {
    id: 6,
    name: "Learning Gutenberg 6",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 207,
    cart: false,
  },
  {
    id: 7,
    name: "Learning Gutenberg 7",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 337,
    cart: false,
  },
  {
    id: 8,
    name: "Learning Gutenberg 8",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 208,
    cart: false,
  },
  {
    id: 9,
    name: "Learning Gutenberg 9",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 146,
    cart: false,
  },
  {
    id: 10,
    name: "Learning Gutenberg 10",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 398,
    cart: false,
  },
  {
    id: 11,
    name: "Learning Gutenberg 11",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 118,
    cart: false,
  },
  {
    id: 12,
    name: "Learning Gutenberg 12",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 376,
    cart: false,
  },
  {
    id: 13,
    name: "Learning Gutenberg 13",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 291,
    cart: false,
  },
  {
    id: 14,
    name: "Learning Gutenberg 14",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 156,
    cart: false,
  },
  {
    id: 15,
    name: "Learning Gutenberg 15",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 243,
    cart: false,
  },
  {
    id: 16,
    name: "Learning Gutenberg 16",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 238,
    cart: false,
  },
  {
    id: 17,
    name: "Learning Gutenberg 17",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 127,
    cart: false,
  },
  {
    id: 18,
    name: "Learning Gutenberg 18",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 382,
    cart: false,
  },
  {
    id: 19,
    name: "Learning Gutenberg 19",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 322,
    cart: false,
  },
  {
    id: 20,
    name: "Learning Gutenberg 20",
    desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
    price: 288,
    cart: false,
  },
//   {
//     id: 21,
//     name: "Learning Gutenberg 21",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 268,
//     cart: false,
//   },
//   {
//     id: 22,
//     name: "Learning Gutenberg 22",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 299,
//     cart: false,
//   },
//   {
//     id: 23,
//     name: "Learning Gutenberg 23",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 359,
//     cart: false,
//   },
//   {
//     id: 24,
//     name: "Learning Gutenberg 24",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 380,
//     cart: false,
//   },
//   {
//     id: 25,
//     name: "Learning Gutenberg 25",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 184,
//     cart: false,
//   },
//   {
//     id: 26,
//     name: "Learning Gutenberg 26",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 228,
//     cart: false,
//   },
//   {
//     id: 27,
//     name: "Learning Gutenberg 27",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 252,
//     cart: false,
//   },
//   {
//     id: 28,
//     name: "Learning Gutenberg 28",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 290,
//     cart: false,
//   },
//   {
//     id: 29,
//     name: "Learning Gutenberg 29",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 221,
//     cart: false,
//   },
//   {
//     id: 30,
//     name: "Learning Gutenberg 30",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 133,
//     cart: false,
//   },
//   {
//     id: 31,
//     name: "Learning Gutenberg 31",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 276,
//     cart: false,
//   },
//   {
//     id: 32,
//     name: "Learning Gutenberg 32",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 361,
//     cart: false,
//   },
//   {
//     id: 33,
//     name: "Learning Gutenberg 33",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 261,
//     cart: false,
//   },
//   {
//     id: 34,
//     name: "Learning Gutenberg 34",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 369,
//     cart: false,
//   },
//   {
//     id: 35,
//     name: "Learning Gutenberg 35",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 313,
//     cart: false,
//   },
//   {
//     id: 36,
//     name: "Learning Gutenberg 36",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 185,
//     cart: false,
//   },
//   {
//     id: 37,
//     name: "Learning Gutenberg 37",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 350,
//     cart: false,
//   },
//   {
//     id: 38,
//     name: "Learning Gutenberg 38",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 192,
//     cart: false,
//   },
//   {
//     id: 39,
//     name: "Learning Gutenberg 39",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 216,
//     cart: false,
//   },
//   {
//     id: 40,
//     name: "Learning Gutenberg 40",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 207,
//     cart: false,
//   },
//   {
//     id: 41,
//     name: "Learning Gutenberg 41",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 112,
//     cart: false,
//   },
//   {
//     id: 42,
//     name: "Learning Gutenberg 42",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 360,
//     cart: false,
//   },
//   {
//     id: 43,
//     name: "Learning Gutenberg 43",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 243,
//     cart: false,
//   },
//   {
//     id: 44,
//     name: "Learning Gutenberg 44",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 365,
//     cart: false,
//   },
//   {
//     id: 45,
//     name: "Learning Gutenberg 45",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 285,
//     cart: false,
//   },
//   {
//     id: 46,
//     name: "Learning Gutenberg 46",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 388,
//     cart: false,
//   },
//   {
//     id: 47,
//     name: "Learning Gutenberg 47",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 269,
//     cart: false,
//   },
//   {
//     id: 48,
//     name: "Learning Gutenberg 48",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 131,
//     cart: false,
//   },
//   {
//     id: 49,
//     name: "Learning Gutenberg 49",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 313,
//     cart: false,
//   },
//   {
//     id: 50,
//     name: "Learning Gutenberg 50",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 328,
//     cart: false,
//   },
//   {
//     id: 51,
//     name: "Learning Gutenberg 51",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 392,
//     cart: false,
//   },
//   {
//     id: 52,
//     name: "Learning Gutenberg 52",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 101,
//     cart: false,
//   },
//   {
//     id: 53,
//     name: "Learning Gutenberg 53",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 369,
//     cart: false,
//   },
//   {
//     id: 54,
//     name: "Learning Gutenberg 54",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 381,
//     cart: false,
//   },
//   {
//     id: 55,
//     name: "Learning Gutenberg 55",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 233,
//     cart: false,
//   },
//   {
//     id: 56,
//     name: "Learning Gutenberg 56",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 106,
//     cart: false,
//   },
//   {
//     id: 57,
//     name: "Learning Gutenberg 57",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 385,
//     cart: false,
//   },
//   {
//     id: 58,
//     name: "Learning Gutenberg 58",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 253,
//     cart: false,
//   },
//   {
//     id: 59,
//     name: "Learning Gutenberg 59",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 253,
//     cart: false,
//   },
//   {
//     id: 60,
//     name: "Learning Gutenberg 60",
//     desc: "Lorem ipsum dolor sit amet consectetur. Congue lacus ...",
//     price: 301,
//     cart: false,
//   },
];
